# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  workflow_dispatch:
    inputs:
      tag_ver:
        description: The tag name to use
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
      env:
        CI: true
    #- run: npm test
    - run: npm run build
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
        tag: ${{ github.event.inputs.tag_ver }}